// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Conntrack = newAsset("conntrack.c", "1e57872a3979eb8702a04c935c51ba3672e312d9125172c1700c48e24d8f20c2")
