// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Conntrack = newAsset("conntrack.c", "76d0b578d2829ff680c3bc0641eb58ede6955a8959e1d2ee676f0dd6e2b32136")
