// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Conntrack = newAsset("conntrack.c", "32f69934bbe726302bf0a2776d36aa4c4999b0c25d89c041dc28284e62c613da")
