// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Http = newAsset("http.c", "4cffbe06c1300e447acc7b9d11ad2bf0083be74d05c6ff06c3171755ceeba4cd")
