// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Http = newAsset("http.c", "7fd51b710c855f6983cd9a22eeda0372a71a039261d57ff6b816c747db1e8cc4")
