// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Http = newAsset("http.c", "de592c7096ed434fdb1e6e792e8fd10fb3a3abde6559988b5ef7b7ecfc39e77f")
