// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var OomKill = newAsset("oom-kill.c", "fadd106bf5410c7c89a6238c1aa0b71b41bd56b3fd2ee2c49bbd6a01ff57dd27")
