// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var OomKill = newAsset("oom-kill.c", "6694b74b454e9a0078bf346fae122dca245f90abcac466a11a83999bc17d7cf2")
