// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var OomKill = newAsset("oom-kill.c", "081cc86271cb65dd17a1271d2681310c0d81827bbb6f30a09669d1b5e616f928")
