// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var RuntimeSecurity = newAsset("runtime-security.c", "b721cd6836533c71a91e8c9d18b929b823f3b328d66b64da21a6618a07b734cf")
