// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var RuntimeSecurity = newAsset("runtime-security.c", "4457c5c3827bebfb38fedb98693ee651baa61936318a0b8b14398e5ab1fb6794")
