// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var RuntimeSecurity = newAsset("runtime-security.c", "4e0443f8278cf0695dc23be6bd36a99e26d1ff4db3c8456628eda9b3288cf1b5")
