// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var TcpQueueLength = newAsset("tcp-queue-length.c", "658f5e36c034e4b687a38d112bfaf6735f3b615fb9b12da6b4e2c217da2b5aed")
