// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var TcpQueueLength = newAsset("tcp-queue-length.c", "d2e9274380561196fb292b78ba66c86b4b558463edd8b39c98f1242849e9977e")
