// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var TcpQueueLength = newAsset("tcp-queue-length.c", "b2441aac4c87e22fad19fe717829a1863a42aab4af16d0f97a701dfe2c5c907f")
