// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Tracer = newAsset("tracer.c", "403a5a4fe262d85d6ab25c769b84701fba5eb007268da67ea63f3d05910d5f55")
