// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Tracer = newAsset("tracer.c", "e178538b59ae340886cd8b1821f91dd7de700a03a5bc7a9532f04638cdca7df0")
