// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Tracer = newAsset("tracer.c", "15497c1c4b56bc242b12495d716119da6668fef738a3d7671989a73baf92ee73")
